### ISSUE TITLE
Move the projects to a github org?

### ISSUE THREAD

**Issue by arunoruto** [tokyo-night/tokyo-night-vscode-theme#84]
I love the theme and would love to see a bundles page with all the possible implementations for different programs like it's done with [catppuccin](https://github.com/catppuccin/). I noticed a GitHub org at https://github.com/tokyo-night, but there are only templates and wallpapers, but no themes. Maybe one could move the projects there so people get a better overview :)

**Comment by enkia** [comment]
Done!
