### ISSUE TITLE
tsx and jsx unharmonized 

### ISSUE THREAD

**Issue by QuentinVdr** [tokyo-night/tokyo-night-vscode-theme#86]
Is that wanted to get some unharmonized color syntax between jsx and tsx ? 
Specially for props at the bottom and import variable

![image](https://github.com/enkia/tokyo-night-vscode-theme/assets/56938113/62c02c3e-4e24-4acb-80b5-341a292c70eb)
![image](https://github.com/enkia/tokyo-night-vscode-theme/assets/56938113/b6f91846-9710-461d-8094-778d47918672)

**Comment by enkia** [comment]
Well, tsx has better textmate scopes and semantic token support so in a sense, I'm intentionally using them?

**Comment by QuentinVdr** [comment]
Oh, that makes sens. 
And no problem, I was just curious if it was just different on purpose or by technical limit. 
Thanks for the response.
